spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: onboard
    password: onboard
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    
springdoc:
  swagger-ui:
    path: /swagger
    
